### ISSUE TITLE
Some data fail to download from vayla.fi

### ISSUE THREAD

**Issue by mathias-nyman** [vokkim/finnish-nautical-chart-vectors#13]
Four data files fail to download from vayla.fi using the `import/fetch-csv-from-vayla.sh` script. Any help on this would be much appreciated.

The errors:
```
$ cat data/syvyysalue.csv data/syvyyskayra.csv data/syvyyspiste.csv data/rantarakenteet.csv
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://julkinen.vayla.fi/geoserver/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="InvalidParameterValue" locator="typeName">
<ows:ExceptionText>Feature type rajoitettu:syvyysalue_a unknown</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://julkinen.vayla.fi/geoserver/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="InvalidParameterValue" locator="typeName">
<ows:ExceptionText>Feature type rajoitettu:syvyyskayra_v unknown</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://julkinen.vayla.fi/geoserver/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="InvalidParameterValue" locator="typeName">
<ows:ExceptionText>Feature type rajoitettu:syvyyspiste_p unknown</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://julkinen.vayla.fi/geoserver/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="InvalidParameterValue" locator="typeName">
<ows:ExceptionText>Feature type avoin:rantarakenteet_v unknown</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

Perhaps these have been redacted from the vayla.fi dataset or the parameter names have changed?
The reported invalid parameters are not listed in the "documentation", nor could I find any similar parameter names however:
https://julkinen.vayla.fi/inspirepalvelu/rajoitettu/wfs?request=GetCapabilities
https://julkinen.vayla.fi/inspirepalvelu/avoin/wfs?request=GetCapabilities

**Comment by mathias-nyman** [comment]
This seems like the culprit:

> 16.4.2020
Poistetaan merikartoituksen aineistoja.
Liikenne- ja viestintävirasto Traficom on eriyttänyt Väyläviraston paikkatietopalveluista sen vastuulla olevat merikartoituksen katselu- ja latauspalvelut.
Uudet osoitteet ja rajapintakutsut ovat muotoa:
https://julkinen.traficom.fi/oskari/Tämä on ulkoinen linkki
https://julkinen.traficom.fi/inspirepalvelu/avoin/wms?request=getcapabilitiesTämä on ulkoinen linkki
Syvyysmittausaineistojen tiedostopaketit ovat edelleen ladattavissa Väyläviraston aineistovälitysalustanTämä on ulkoinen linkki kautta.
Palvelut löytyvät jatkossa myös kansallisesta paikkatietoikkunasta ja metatiedot vastaavasti paikkatietohakemistosta. Siirtymäkauden aikana tiedoissa voi esiintyä joitain epätäsmällisyyksiä.
Lisätietoa merikartoituksen paikkatietopalveluista löytyy Liikenne- ja viestintäviraston verkkosivuilta:
https://traficom.fi/fi/tilastot-ja-julkaisut/paikkatietoaineistotTämä on ulkoinen linkki
Mahdolliset kyselyt pyydämme osoittamaan sähköpostiin:  copyright@traficom.fi

https://vayla.fi/vaylista/aineistot/avoindata/ajankohtaista

**Comment by mathias-nyman** [comment]
The above pull request should resolve this issue. If anyone has the prior equivalent datasets from vayla.fi please confirm that these new datasets from traficom.fi are analoguous to them.

I have no base knowledge whatsoever of these different datasets, where they're hosted and how to access them, so I'll document how I stumbled my way to these replacement datasets for anyone having to do the same again:

1.  I googled "rantarakenteet inspirepalvelu" which pointed me to this https://www.opendata.fi/data/fi/dataset/traficomin-avoin-wms/resource/f7b03026-ac9c-4bdf-afbd-9fd21e144ad2
2. The above page on opendata.fi lists the "rantarakenteet_v" with a link to the API description https://julkinen.traficom.fi/inspirepalvelu/avoin/wms?request=getcapabilities
3. Only the 'wms' variant (not the 'wfs'!) includes a mention of "rantarakenteet" within a Style attribute. The Style attribute is inside of Layer named "DepthContour_L".
4. Well, actually there are two Style attributes, one a line and another a point, inside "DepthContour_L" and "DepthContour_P" respectively. The dataset for "DepthContour_P" only contains one entry so L is probably what we want. Also 'v' is probably from "viiva" which corresponds to "Line".
5. Assuming a similar API structure for the "rajattu" datasets, I founds the other three missing layer names mentioned in Style attributes on here: https://julkinen.traficom.fi/inspirepalvelu/rajoitettu/wms?request=getcapabilities

**Comment by mathias-nyman** [comment]
> The above pull request should resolve this issue.
Woulda coulda shoulda.. The above pull request is now confirmed to resolve this issue and can be merged.

**Comment by vokkim** [comment]
Great, I'll try to take a look :)
